services:
  skufy_server:
    build:
      context: .
      dockerfile: skufy_server/Dockerfile
    image: skufy-server:local
    container_name: skufy_server
    network_mode: host
    command: ["--config", "skufy_server/config.json"]
